name: biometrics
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sensors_plus: ^5.0.1
  csv: ^6.0.0
  path_provider: ^2.1.3
  flutter_email_sender: ^6.0.3
  share_plus: ^9.0.0
  cross_file: ^0.3.4+2
  flutter_background_service: ^5.0.5
  flutter_local_notifications: ^17.1.1
  permission_handler: ^11.3.1
 # background_fetch: ^1.3.4
  workmanager: ^0.5.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
